title: Adrian Samatan
name: Adrian
email: contact@adriansamatan.com
description: Computer Science Engineering student

# remote_theme: jameshamann/jekyll-material-theme

parallax_image_one: assets/images/classy_fabric.png # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: Meteor Discourse SSO
project_one_description: A login service for Meteor using Discourse SSO as a provider.
project_one_url: https://github.com/Sakerdot/accounts-discourse
project_one_icon: account_box # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: cplusplus
  - name: python
  - name: java
  - name: linux
  - name: git
  - name: javascript
  - name: jquery
  - name: django
  - name: c
  - name: bootstrap
  - name: css3
  - name: html5
  - name: meteor
  - name: mysql
  - name: postgresql
  - name: typescript

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/Sakerdot
# medium: https://medium.com

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: http://www.adriansamatan.com/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  # - jekyll-remote-theme
